version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:3000"  
    depends_on:
      - server
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:4000  

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"  
    environment:
      - POSTGRES_USER=postgres            
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=learningplan
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=database
      - ACCESS_TOKEN_SECRET=UXhkvb0EqCi5uFgjefiOBUwySWSbWOf07ERoVdispXVla4RXQLWDBigLt99mSvI3
      - REFRESH_TOKEN_SECRET=UTDefpAEyREXmgCkK04pL1SXK6jrB2tEc2ZyMbrFs61THq2y3bpRZOCj5RiPoZGa
      - SERVICE=Outlook
      - HOST=smtp.office365.com
      - EMAIL_PORT=587
      - ACCOUNT_EMAIL=Dummy2377@outlook.com
      - ACCOUNT_PASSWORD=ptic43vr
    depends_on:
      - database

  database:
    image: postgres:12
    environment:          
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: learningplan
    ports:
      - "5432:5432"                       
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./server/database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pg_data:
    driver: local
