version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:3000"  
    depends_on:
      - server
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:4000  

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"  
    environment:
      - POSTGRES_USER=username            
      - POSTGRES_PASSWORD=password        
      - POSTGRES_DATABASE=databasename    
      - POSTGRES_PORT=5432                
      - POSTGRES_HOST=db                 
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: databasename           
      POSTGRES_USER: username             
      POSTGRES_PASSWORD: password         
    ports:
      - "5432:5432"                       
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/learningPlanDB.sql:/docker-entrypoint-initdb.d/learningPlanDB.sql 

volumes:
  pgdata: