POST http://localhost:4000/api/module/get
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.ZXhhbXBsZUBnbWFpbC5jb20.QtBKdF81mLig29pBrpm4BtWNJQ6-LolH-t8aAUCsVic

{
    "email": "example@gmail.com"
}
