POST http://localhost:4000/api/module
content-type: application/json

{
    "name": "your_module",
    "description": "OwO What's this?",
    "completion-percent": 0,
    "email": "example@bsu.edu"
}
